// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbuqoieffjdckyqevshv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1idXFvaWVmZmpkY2t5cWV2c2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyOTA1NTAsImV4cCI6MjA4OTg2NjU1MH0.rCGvbDATNIUfT0ToafFzaDZnkt2xyIEn9G5xo7H2Hac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});